const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const time=s=>s?new Date(s).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'}):'--:--';
const date=s=>s?new Date(s).toLocaleDateString('zh-CN',{month:'2-digit',day:'2-digit'}):'--/--';
function worldLabel(x){const v=String(x.worldName||x.worldId||'').toLowerCase();const special={private:'私人房间',offline:'离线',traveling:'传送中',local:'本地房间'};if(special[v])return special[v];if(x.worldName)return x.worldName;if(String(x.worldId||'').startsWith('wrld_'))return '未知世界';return x.worldId||'未公开位置'}
function parseLoc(loc){if(!loc)return null;const r={worldId:null,instanceId:null,type:null,ownerId:null,region:null};const sep=loc.indexOf(':');r.worldId=sep>=0?loc.slice(0,sep):loc;const rest=sep>=0?loc.slice(sep+1):'';const im=rest.match(/^([^~]+)/);if(im)r.instanceId=im[1];const tm=rest.match(/~((?:friends\+|private|hidden|friends|group|public))\(([^)]+)\)/);if(tm){r.type=tm[1];r.ownerId=tm[2];if(r.type==='private'&&/~canRequestInvite\b/.test(rest))r.type='invite+'}else if(/~local\b/.test(rest)){r.type='local'}else if(im){r.type='public'}const rm=rest.match(/~region\(([^)]+)\)/);if(rm)r.region=rm[1];return r}
function locLabel(loc){const p=parseLoc(loc);if(!p)return '';const t=p.type?({private:'Private',hidden:'Friends+',friends:'Friends',group:'Group',public:'Public',local:'Local'}[p.type]||p.type):'';const parts=[t,p.region?p.region.toUpperCase():''].filter(Boolean);return parts.join(' · ')}
function imgProxy(url){if(!url||typeof url!=='string')return url;if(url.startsWith('/api/dashboard/image-proxy'))return url;if(!/^https:\/\/(api\.vrchat\.cloud|d348imysud55la\.cloudfront\.net|assets\.vrchat\.com|files\.vrchat\.cloud)\//.test(url))return url;return'/api/dashboard/image-proxy?url='+encodeURIComponent(url)}   // 不带 token：该路由被 auth-guard 无条件豁免（issue #217）
function img(url,cls='avatar',online=false,status='',trustLevel='',letter=''){url=imgProxy(url);const sc=statusCls(status);const ph=!url&&(trustLevel||letter)?`<i style="color:#101418;font-style:normal">${esc(letter||'?')}</i>`:'';return `<div class="${cls}${online?' online':''}${sc?' '+sc:''}${!url?' avatar-ph':''}"${url?` style="background-image:url('${esc(url)}')"`:trustLevel?` style="background:${trustColor(trustLevel)}"`:''}>${ph}</div>`}
function statusCls(s){const v=String(s||'').toLowerCase().replace(/[^a-z]/g,'');if(v.includes('web'))return 's-web';if(v.includes('joinme'))return 's-joinme';if(v.includes('askme'))return 's-askme';if(v.includes('busy'))return 's-busy';if(v.includes('active'))return 's-active';if(v.includes('offline'))return 's-offline';return ''}
function isWebOnline(x){if(!x.isOnline)return false;const p=String(x.platform||'').toLowerCase();return p.includes('web')}
function statusDot(s){const c=statusCls(s);return `<i class="status-dot ${c?c.replace('s-','sd-'):'sd-offline'}"></i>`}
function trustBadge(t){if(!t)return '';const v=String(t).toLowerCase();let cls='tb-gray';if(/trusted/.test(v))cls='tb-purple';else if(/known/.test(v))cls='tb-orange';else if(/new/.test(v))cls='tb-blue';else if(/user/.test(v))cls='tb-green';else if(/team|moderator|staff/.test(v))cls='tb-red';return `<span class="trust-badge ${cls}">${esc(String(t))}</span>`}
function eventType(t){return t==='friend-online'?'online':t==='friend-offline'?'offline':t==='friend-update'||t==='friend-active'||t==='friend-add'||t==='friend-delete'||t==='user-update'?'update':''}

function trustColor(t){if(!t)return'';const v=String(t).toLowerCase();if(/trusted/.test(v))return'#b48ce0';if(/known/.test(v))return'#f09e41';if(/new/.test(v))return'#6ab0de';if(/user/.test(v))return'#7fc46b';if(/team|moderator|staff/.test(v))return'#e06666';return'#8a94a0'}
function fmtMin(m){if(!m&&m!==0)return'';m=Math.round(m);if(m<60)return m+' 分钟';const h=Math.floor(m/60),r=m%60;return r?(h+' 小时 '+r+' 分钟'):(h+' 小时')}